Fix out-of-range file descriptor error in `getdents` syscall
Lind-Project/RawPOSIX pull request #17
Opened 2024-09-19 19:08 UTC by ChinmayShringi

Fixes # (issue)

 
This PR addresses an issue in the `getdents` syscall where out-of-range file descriptors (beyond `FD_PER_PROCESS_MAX`) were not handled correctly, leading to index out-of-bounds errors. A bounds check has been added to `translate_virtual_fd` to ensure that file descriptors beyond the allowed range return an `EBADFD` error instead of panicking.

This change prevents potential crashes and ensures that the system handles file descriptor limits gracefully.

There are no new dependencies required for this change.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

The changes have been tested by running the `ut_lind_fs_getdents_out_of_range_fd` test, which verifies that the system now correctly returns an error for file descriptors out of range.

- Run the test case: `RUST_BACKTRACE=full cargo test tests::fs_tests::fs_tests::ut_lind_fs_getdents_out_of_range_fd`
- Observe that the error handling for out-of-range file descriptors is now functioning correctly.

Tested on the following environment:
- Docker container with Linux-based system.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-09-19 20:54 UTC, Yaxuan-w commented
Can we add this check in `fs_calls.rs`?

2024-09-19 20:54 UTC, Yaxuan-w reviewed
Can we add this to `fs_calls.rs`?

2024-09-19 23:02 UTC, rennergade commented
@JustinCappos is this a bug we should handle in fdtables or the individual system calls?

2024-09-23 18:45 UTC, JustinCappos requested changes

2024-09-23 18:45 UTC, JustinCappos commented on src/fdtables/dashmapvecglobal.rs
> +    // Below condition checks if the virtualfd is out of bounds and if yes it throws an error
Note that 
```suggestion
    // Below condition checks if the virtualfd is out of bounds and if yes it throws an error
    // Note that this assumes that all virtualfd numbers returned < FD_PER_PROCESS_MAX 
```

2024-09-23 19:09 UTC, merged