Fix `ut_lind_fs_mkdir_invalid_modebits`
Lind-Project/RawPOSIX pull request #43
Opened 2024-09-28 18:51 UTC by ChinmayShringi

Fixes # (issue)

This update modifies `mkdir_syscall` to properly handle and reject invalid mode bits when creating a directory. If the mode includes bits outside the valid range (`0o0000` to `0o0777`), the syscall now returns an `EPERM` error, indicating that the permission bits are not valid. This change ensures consistent behavior in accordance with POSIX standards, preventing directories from being created with unsupported or incorrect permissions.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- `cargo test ut_lind_fs_mkdir_invalid_modebits`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-09-29 17:03 UTC, Yaxuan-w commented on src/safeposix/syscalls/fs_calls.rs
> +        }
what is currently rawposix returned in this situation?

2024-09-29 20:27 UTC, ChinmayShringi commented on src/safeposix/syscalls/fs_calls.rs
> +        }
Currently it return a -1 value

2024-09-30 17:45 UTC, Yaxuan-w commented on src/safeposix/syscalls/fs_calls.rs
> +        }
Could you test with [`get_errno()`](https://github.com/Lind-Project/RawPOSIX/blob/98fedeab93440d63b69e044ca81a3da5f84220d5/src/interface/misc.rs#L139) to see the errno returned by libc::mmap?

Sth like:
```rust
let ret = libc::mmap(...)
if ret < 0 {
  println!(get_errno());
}
```

2024-10-09 14:05 UTC, Yaxuan-w approved these changes
LGTM

2024-10-09 14:07 UTC, Yaxuan-w requested changes
sry for the confusion

2024-10-09 14:07 UTC, Yaxuan-w commented on src/safeposix/syscalls/fs_calls.rs
> +        }
This case should be handled in rust libc as well... So we don't need those checks

2024-10-22 20:11 UTC, Yaxuan-w approved these changes
lgtm

2024-10-23 16:58 UTC, merged